#!/usr/bin/env bash

set -e

fancy_echo() {
  printf "\n%b\n" "$1"
}

fancy_echo "Installing i3 ..."

sudo sh -c "echo 'deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe' >> /etc/apt/sources.list"
sudo apt-get -y update
sudo apt-get -y --allow-unauthenticated install sur5r-keyring
sudo apt-get -y update
sudo apt-get -y install i3


if [ -d "$HOME/.i3" ]
then
  fancy_echo "i3 config folder already exist. Saving a copy ..."
  mv ~/.i3 ~/.i3.backup
fi

if [ -f "$HOME/.i3status.conf" ]
then
  fancy_echo "i3status.conf already exist. Saving a copy ..."
  mv ~/.i3status.conf ~/.i3status.conf.backup
fi

git clone https://github.com/alfredormz/i3-config.git ~/.i3

ln -s ~/.i3/i3status.conf ~/.i3status.conf
